languageCode = "en"
languageName = "English"
weight = 1
title = "Opensource SSP Server"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo_transparent.png"
  description = "Opensource SSP Server for internal use and monetization"

# [author]
#   name = "Blowfish"
#   image = "img/logo_transparent.png"
#   headline = "A powerful, lightweight theme for Hugo."
#   bio = "A powerful, lightweight theme for Hugo."
#   links = [
#     { x-twitter = "https://twitter.com/burufugu" },
#     { github = "https://github.com/nunocoracao/blowfish" },
#   ]